src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\DateTime;

#[ORM\Entity(repositoryClass: BookRepository::class)]
class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'string', length: 255)]
    private $author;

    #[ORM\Column(type: 'string', length: 255)]
    private $ISBN;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $description;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $release_date;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $img;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $category;

    #[ORM\Column(type: 'string', length: 100, nullable: true)]
    private $language;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getISBN(): ?int
    {
        return $this->ISBN;
    }

    public function setISBN(int $ISBN): self
    {
        $this->ISBN = $ISBN;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getReleaseDate(): ?\DateTime
    {
        return $this->release_date;
    }

    public function setReleaseDate(string $release_date): self
    {
        $this->release_date = new \DateTime($release_date);

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(?string $img): self
    {
        $this->img = $img;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(?string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getLanguage(): ?string
    {
        return $this->language;
    }

    public function setLanguage(?string $language): self
    {
        $this->language = $language;

        return $this;
    }
}

src/Controller/BookController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Doctrine\Persistence\ManagerRegistry;
use App\Repository\BookRepository;
use App\Entity\Book;
use Symfony\Component\Validator\Constraints\DateTime;

class BookController extends AbstractController
{
    #[Route('/book', name: 'app_book')]
    public function index(): Response
    {
        return $this->render('book/index.html.twig', [
            'controller_name' => 'BookController',
        ]);
    }

    /**
    * @Route("/book/add",
    *      name="add_book",
    *      methods={"GET"})
    */
    public function add(): Response
    {
        $title = "Add book";
        return $this->render('book/add.html.twig', [
            'title' => $title
        ]);
    }

    /**
     * Set book attributes for edit/add book
     *
     * @param Book $book
     * @param mixed $title
     * @param mixed $description
     * @param mixed $img
     * @param mixed $author
     * @param mixed $release
     * @param mixed $isbn
     * @param mixed $category
     * @param mixed $language
     * @return void
     */
    public function setBookAttr(
        Book $book,
        mixed $title,
        mixed $description,
        mixed $img,
        mixed $author,
        mixed $release,
        mixed $isbn,
        mixed $category,
        mixed $language
    ): void {
        $book->setTitle($title);
        $book->setDescription($description);
        $book->setImg($img);
        $book->setAuthor($author);
        $book->setReleaseDate($release);
        $book->setISBN(intval($isbn));
        $book->setCategory($category);
        $book->setLanguage($language);
    }

    /**
    * @Route("/book/add",
    *      name="add_book_process",
    *      methods={"POST"})
    */
    public function addBookProcess(
        Request $request,
        ManagerRegistry $doctrine
    ): Response {

        $entityManager = $doctrine->getManager();

        $book = new Book();
        $this->setBookAttr(
            $book,
            $request->request->get("title"),
            $request->request->get("description"),
            $request->request->get("img"),
            $request->request->get("author"),
            $request->request->get("release"),
            $request->request->get("isbn"),
            $request->request->get("category"),
            $request->request->get("language")
        );

        $entityManager->persist($book);

        $entityManager->flush();

        // return $this->json($result);
        return $this->redirectToRoute('book_show_all');
    }

    /**
    * @Route("/book/show", name="book_show_all")
    */
    public function showAllBooks(
        Bookrepository $bookRepository
    ): Response {
        $books = $bookRepository
            ->findAll();

        $title = "All books";

        // return $this->json($books);
        return $this->render('book/show-all.html.twig', [
            'title' => $title,
            'books' => $books
        ]);
    }

    /**
     * @Route("/book/show/{bookId}", defaults={"bookId" = 1}, name="book_by_id", methods={"GET"})
     */
    public function showBook(
        BookRepository $bookRepository,
        int $bookId
    ): Response {
        $book = $bookRepository
            ->find($bookId);


        // return $this->json($book);
        return $this->render('book/show-one.html.twig', [
            'book' => $book
        ]);
    }

    /**
     * @Route("/book/edit/{bookId}",
     *      defaults={"bookId" = 1},
     *      name="edit-book",
     *      methods={"GET"})
     */
    public function editBook(
        BookRepository $bookRepository,
        int $bookId
    ): Response {
        $book = $bookRepository
            ->find($bookId);

        $title = "Update";


        // return $this->json($book);
        return $this->render('book/update.html.twig', [
            'title' => $title,
            'book' => $book
        ]);
    }

    /**
     * @Route("/book/edit/{bookId}", defaults={"bookId" = 1}, name="edit-book-process",
     *      methods={"POST"})
     */
    public function editBookProcess(
        Request $request,
        ManagerRegistry $doctrine
    ): Response {

        $entityManager = $doctrine->getManager();
        $book = $entityManager->getRepository(Book::class)->find($request->request->get("id"));

        if (!$book) {
            throw $this->createNotFoundException(
                'No book found for id ' . $request->request->get("id")
            );
        }

        $this->setBookAttr(
            $book,
            $request->request->get("title"),
            $request->request->get("description"),
            $request->request->get("img"),
            $request->request->get("author"),
            $request->request->get("release"),
            $request->request->get("isbn"),
            $request->request->get("category"),
            $request->request->get("language")
        );

        $entityManager->flush();

        // return $this->json($book);
        return $this->redirectToRoute('book_by_id', ["bookId" => $request->request->get("id")]);
    }

    /**
     * @Route("/book/delete/{bookId}", name="delete-book")
     */
    public function deleteBook(
        ManagerRegistry $doctrine,
        int $bookId
    ): Response {
        $entityManager = $doctrine->getManager();
        $book = $entityManager->getRepository(Book::class)->find($bookId);

        if (!$book) {
            throw $this->createNotFoundException(
                'No book found for id ' . $bookId
            );
        }

        $entityManager->remove($book);
        $entityManager->flush();

        return $this->redirectToRoute('book_show_all');
    }
}

templates/book/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add book{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">

    <h1> {{ title }}</h1>
    {% include 'form/book/insert.html.twig'%}
  
</div>
{% endblock %}

templates/book/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BookController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Bibliotek</h1>

     <div class="row">
            <div class="column"><a href="{{ path('add_book') }}">Lägg till bok</a></div>
            <div class="column"><a href="{{ path('book_show_all') }}">Tillgängliga böcker</a></div>
    </div>

    {# This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/Users/malinolsson/dbwebb-kurser/mvc/me/report/src/Controller/BookController.php'|file_link(0) }}">src/Controller/BookController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/Users/malinolsson/dbwebb-kurser/mvc/me/report/templates/book/index.html.twig'|file_link(0) }}">templates/book/index.html.twig</a></code></li>
    </ul> #}
</div>
{% endblock %}

templates/book/show-all.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add book{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">

    <h1> {{ title }}</h1>
    <div class="book-item-container">
    {% if (books != null)%}
    {% for book in books %}
        <a href="{{ path("book_by_id", {'bookId': book.id }) }}">
            <div class="book-item">
                <p>{{ book.title }}</p>
                <p>{{ book.author }}</p>
            </div>
        </a>
    {% endfor %}
    {% else %}
    <h3> Inga böcker att visa än </h3>
    {% endif %}
    </div>
</div>
{% endblock %}

templates/book/show-one.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add book{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">

    
    <div class="book-container">

    <div class="book-img">
        {% if (book.img) %}
        <img  src="{{ asset(book.img) }}">
        {% endif %}
        <div>
            <h6>Kategori: {{book.category}}</h6>
            <h6>Språk: {{book.language}}</h6>
            <h6>Utgivningsdatum: {{book.releaseDate|date('Y-m-d') }}</h6>
            <h6>ISBN: {{book.isbn}}</h6>
        </div>
    </div>
    <div class="book-info">
        <h2>{{book.title}}</h2>
        <h5>{{book.author}}</h5>

        <p>{{book.description}}</p>
    </div>
    </div>
    <div>
    <a href={{ path("book_show_all")}}><h5>&larr; Tillbaka</h5></a>
    <a href={{ path("edit-book", {"bookId": book.id })}}><button>Update</button></a>
    <a href={{ path("delete-book", {"bookId": book.id })}}><button>Delete</button></a>
    </div>
</div>
{% endblock %}

templates/book/update.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add book{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">

    <h1> {{ title }}</h1>
    {% include 'form/book/update.html.twig'%}
    <a href={{ path("book_by_id", {"id": book.id })}}><h5>&larr; Tillbaka</h5></a>
</div>
{% endblock %}